networks:
  streaming-network:
    external: true
    name: music-streaming_streaming-network

services:
  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - streaming-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  superset:
    image: apache/superset:latest
    container_name: superset
    networks:
      - streaming-network
    depends_on:
      - redis
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: 'music_streaming_superset_secret'
      SUPERSET_LOAD_EXAMPLES: 'no'
      POSTGRES_DB: music_streaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # Configure Superset to use PostgreSQL for metadata
      SQLALCHEMY_DATABASE_URI: 'postgresql://postgres:postgres@postgres:5432/music_streaming'
      # Configure Redis for rate limiting
      FLASK_APP: 'superset'
      SUPERSET_REDIS_HOST: 'redis'
      SUPERSET_REDIS_PORT: '6379'
    volumes:
      - superset_home:/app/superset_home
      - ./superset_init.sh:/app/superset_init.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      bash -c "chmod +x /app/superset_init.sh && /app/superset_init.sh"

volumes:
  superset_home:
