version: '3'

networks:
  streaming-network:
    external: true

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    networks:
      - streaming-network
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: 'music_streaming_superset_secret'
      SUPERSET_LOAD_EXAMPLES: 'no'
      POSTGRES_DB: music_streaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - superset_home:/app/superset_home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      bash -c "superset db upgrade &&
              superset fab create-admin
                        --username admin
                        --firstname Admin
                        --lastname User
                        --email admin@example.com
                        --password admin &&
              superset init &&
              superset run -p 8088 --with-threads --reload --debugger"

volumes:
  superset_home: